version: '3.8'

services:
  pyteur:
    build: .
    container_name: pyteur_app
    command: /bin/sh -c "if [ \"$RESET_DB\" = \"true\" ]; then python manage.py --reset --init; else python manage.py --init; fi && python run.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./.env:/app/.env  # Monte le fichier .env dans le conteneur
    environment:
      - FLASK_ENV=development
      - RESET_DB=false    # Mettre à true pour forcer la réinitialisation complète
      - SECRET_KEY=your_secret_key
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: /bin/sh -c "ollama serve & sleep 5 && ollama pull gemma3:1b && tail -f /dev/null"
    restart: unless-stopped

volumes:
  ollama_data:
