version: '3.8'

services:
  pyteur:
    build:
      context: .
    container_name: pyteur_os
    command: /bin/sh -c "if [ \"$RESET_DB\" = \"true\" ]; then python manage.py --reset --init; else python manage.py --init; fi && gunicorn -c gunicorn_config.py wsgi:app"
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./.env:/app/.env  # Monte le fichier .env dans le conteneur
    environment:
      - FLASK_ENV=production
      - RESET_DB=false    # Mettre à true pour forcer la réinitialisation complète
      - SECRET_KEY=your_secret_key
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull qwen2.5-coder:0.5b && tail -f /dev/null"]
    restart: always

volumes:
  ollama_data:  # Volume pour stocker les modèles Ollama
